accent = "#C9A227"
cursor = "#C9A227"
foreground = "#D9D9D9"
background = "#121212"
selection_foreground = "#D9D9D9"
selection_background = "#926C15"
color0 = "#76520E"
color1 = "#DBB42C"
color2 = "#A47E1B"
color3 = "#FAD643"
color4 = "#926C15"
color5 = "#B69121"
color6 = "#805B10"
color7 = "#EDC531"
color8 = "#805B10"
color9 = "#EDC531"
color10 = "#B69121"
color11 = "#FFEE69"
color12 = "#A47E1B"
color13 = "#C9A227"
color14 = "#DBB42C"
color15 = "#FAD643"
